# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('show', models.BooleanField(default=True, verbose_name='is show')),
                ('url', models.CharField(default='/', max_length=128, verbose_name='url')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='banner/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('miniature', django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='news/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('show', models.BooleanField(default=True, verbose_name='is show')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='advantages/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'our advantages',
                'verbose_name_plural': 'our advantages',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('review', models.TextField(verbose_name='review')),
                ('photo', django_thumbs.db.models.ImageWithThumbsField(default='default-avatar.128x128.jpg', upload_to='review/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
