# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(verbose_name='date of creation'),
        ),
    ]
