# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models
import gross_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to=gross_gallery.models.get_photos_folder)),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
    ]
