# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='catalog/brands/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='special',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('\u041c\u041a\u041f\u041f', '\u041c\u041a\u041f\u041f'), ('\u0410\u041a\u041f\u041f', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='special',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('\u041c\u041a\u041f\u041f', '\u041c\u041a\u041f\u041f'), ('\u0410\u041a\u041f\u041f', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('\u041c\u041a\u041f\u041f', '\u041c\u041a\u041f\u041f'), ('\u0410\u041a\u041f\u041f', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
    ]
