# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170203_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='char_engine_capacity',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='engine capacity'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_engine_capacity',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='engine capacity'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_engine_power',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='engine power'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_engine_capacity',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='engine capacity'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_engine_power',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='engine power'),
        ),
    ]
