# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170210_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_abs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='ABS'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_ebs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='EBS'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_spare_wheel',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='spare wheel'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='char_abs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='ABS'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='char_ebs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='EBS'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='char_spare_wheel',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='spare wheel'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_abs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='ABS'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_ebs',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='EBS'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_spare_wheel',
            field=models.CharField(blank=True, choices=[('\u0414\u0430', 'Yes'), ('', 'No')], default='', max_length=2, null=True, verbose_name='spare wheel'),
        ),
    ]
