# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170210_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043f\u0440\u043e\u0441 \u041a\u041f',
                'verbose_name_plural': '\u0417\u0430\u043f\u0440\u043e\u0441 \u041a\u041f',
            },
        ),
        migrations.AlterModelOptions(
            name='specialphoto',
            options={'ordering': ['pk'], 'verbose_name': 'photo', 'verbose_name_plural': 'photo'},
        ),
        migrations.AlterModelOptions(
            name='tractiveunitphoto',
            options={'ordering': ['pk'], 'verbose_name': 'photo', 'verbose_name_plural': 'photo'},
        ),
        migrations.AlterModelOptions(
            name='trailerphoto',
            options={'ordering': ['pk'], 'verbose_name': 'photo', 'verbose_name_plural': 'photo'},
        ),
        migrations.AlterModelOptions(
            name='truckphoto',
            options={'ordering': ['pk'], 'verbose_name': 'photo', 'verbose_name_plural': 'photo'},
        ),
    ]
