# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170228_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearboxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'gearbox type',
                'verbose_name_plural': 'gearbox types',
            },
        ),
        migrations.CreateModel(
            name='WheelArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'wheel arrangement',
                'verbose_name_plural': 'wheel arrangements',
            },
        ),
        migrations.AlterField(
            model_name='cardrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
