# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170317_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('mkpp', '\u041c\u041a\u041f\u041f'), ('akpp', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='special',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4'), ('test', 'test')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
        migrations.AlterField(
            model_name='special',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_special_related_+', to='catalog.Special', verbose_name='\u043f\u043e\u0445\u043e\u0436\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('mkpp', '\u041c\u041a\u041f\u041f'), ('akpp', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4'), ('test', 'test')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
        migrations.AlterField(
            model_name='tractiveunit',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_tractiveunit_related_+', to='catalog.TractiveUnit', verbose_name='\u043f\u043e\u0445\u043e\u0436\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_trailer_related_+', to='catalog.Trailer', verbose_name='\u043f\u043e\u0445\u043e\u0436\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_gearbox_type',
            field=models.CharField(blank=True, choices=[('mkpp', '\u041c\u041a\u041f\u041f'), ('akpp', '\u0410\u041a\u041f\u041f')], max_length=64, null=True, verbose_name='gearbox type'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='char_wheel_arrangement',
            field=models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6'), ('8x4', '8x4'), ('test', 'test')], max_length=64, null=True, verbose_name='wheel arrangement'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_truck_related_+', to='catalog.Truck', verbose_name='\u043f\u043e\u0445\u043e\u0436\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
    ]
