# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_auto_20170317_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='catalog/photos/%Y-%m-%d/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0447\u0430\u0442\u044c \u041a\u041f',
                'verbose_name_plural': '\u041f\u0435\u0447\u0430\u0442\u044c \u041a\u041f',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('char_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='model')),
                ('char_year_of_issue', models.PositiveSmallIntegerField(verbose_name='year of issue')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('slug', models.CharField(choices=[('special', '\u0421\u043f\u0435\u0446\u0442\u0435\u0445\u043d\u0438\u043a\u0430'), ('tractive-unit', '\u0422\u044f\u0433\u0430\u0447\u0438'), ('trailer', '\u041f\u043e\u043b\u0443\u043f\u0440\u0438\u0446\u0435\u043f\u044b'), ('truck', '\u0413\u0440\u0443\u0437\u043e\u0432\u0438\u043a\u0438')], db_index=True, max_length=20, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('short_description', models.CharField(blank=True, max_length=124, null=True, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('best_offer', models.BooleanField(default=False, verbose_name='best offer')),
                ('video', models.CharField(blank=True, max_length=250, null=True, verbose_name='video id')),
                ('stock', models.BooleanField(default=False, verbose_name='stock')),
                ('sold', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1, verbose_name='sold')),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('char_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Brand', verbose_name='brand')),
                ('char_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Color', verbose_name='colour')),
                ('char_vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.VehicleType', verbose_name='vehicle type')),
                ('equipment', models.ManyToManyField(blank=True, to='catalog.Equipment', verbose_name='equipment')),
                ('related', models.ManyToManyField(blank=True, related_name='_products_related_+', to='catalog.Products', verbose_name='\u0442\u0430\u043a \u0436\u0435 \u043f\u043e\u043a\u0443\u043f\u0430\u044e\u0442')),
                ('related_same', models.ManyToManyField(blank=True, related_name='_products_related_same_+', to='catalog.Products', verbose_name='\u043f\u043e\u0445\u043e\u0436\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='catalog.Products', verbose_name='\u0422\u0435\u0445\u043d\u0438\u043a\u0430')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'characteristic',
                'verbose_name_plural': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='PropItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'characteristic item',
                'verbose_name_plural': 'characteristic itrms',
            },
        ),
        migrations.RemoveField(
            model_name='special',
            name='char_brand',
        ),
        migrations.RemoveField(
            model_name='special',
            name='char_colour',
        ),
        migrations.RemoveField(
            model_name='special',
            name='char_vehicle_type',
        ),
        migrations.RemoveField(
            model_name='special',
            name='related',
        ),
        migrations.RemoveField(
            model_name='special',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='char_brand',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='char_colour',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='char_vehicle_type',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='related',
        ),
        migrations.RemoveField(
            model_name='tractiveunit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tractiveunitphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='char_brand',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='char_colour',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='char_trailer_type',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='char_vehicle_type',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='related',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trailerphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='char_brand',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='char_colour',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='char_vehicle_type',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='related',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='truckphoto',
            name='product',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
        migrations.DeleteModel(
            name='SpecialPhoto',
        ),
        migrations.DeleteModel(
            name='TractiveUnit',
        ),
        migrations.DeleteModel(
            name='TractiveUnitPhoto',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='TrailerPhoto',
        ),
        migrations.DeleteModel(
            name='TrailerType',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='TruckPhoto',
        ),
    ]
