# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170319_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='propitem',
            name='in_filter',
            field=models.BooleanField(default=False, verbose_name='in filter?'),
        ),
    ]
