# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_propitem_in_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propitem',
            options={'ordering': ['order'], 'verbose_name': 'characteristic item', 'verbose_name_plural': 'characteristic itrms'},
        ),
        migrations.AddField(
            model_name='propitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
