# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170319_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='char_mileage',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u043f\u0440\u043e\u0431\u0435\u0433'),
        ),
    ]
