# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:23
from __future__ import unicode_literals

import catalog.models
from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_products_char_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '\u0422\u0435\u0445\u043d\u0438\u043a\u0430', 'verbose_name_plural': '\u0422\u0435\u0445\u043d\u0438\u043a\u0430'},
        ),
        migrations.AlterModelOptions(
            name='propitem',
            options={'ordering': ['order'], 'verbose_name': '\u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430', 'verbose_name_plural': '\u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to=catalog.models.get_dir_name_cat),
        ),
    ]
