# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170328_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new_offer',
            field=models.BooleanField(default=False, verbose_name='new'),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_offer',
            field=models.BooleanField(default=False, verbose_name='sale'),
        ),
    ]
